### ISSUE TITLE
About the data structure of inside outside

### ISSUE THREAD

**Issue by berlino** [harvardnlp/struct-attn#1]
Just a detail about the algorithm given in the paper which uses Esiner's data structure inside[span_start][span_end][left/right][complete/incomplete].  

The paper mentioned that "The third dimension encodes whether  the root of subtree is the left or right index of the span."  However, the code shows the opposite way. For example, the partition \alpha[1][n][R][1] indicates the root is the right index, but I think it's left index since root symbol is the first element. It also happens in the iteration of the inside and outside value.

I guess the result is the same after all, but I just got little confused about the detail. 

Any comments? Thanks

**Comment by yoonkim** [comment]
Hi! Actually the notation in the paper is consistent with the code--it's just that the first dimension of the tensor in the code encodes batch size.

Hope this helps!

**Comment by berlino** [comment]
Thanks for the response!

I may not make myself clear about this. Let me take the pseudocode provided in section B of the paper's appendices for example, the inside log table α is n\*n\*2\*2 where the third dimension encodes whether the root of subtree is the left or right index of the span.

The problem is that in the equation you provided below, I found the "L" or "R" didn't actually mean the "root" of the subtree. 
α[s, t, R, 0] ← logadd u∈[s,t−1] α[s, u, R, 1] ⊗ α[u + 1, t, L, 1] ⊗ θst

Specifically, I think it should be something like this where the third dimension is the opposite as the original according to the Eisner's algorithm.
α[s, t, L, 0] ← logadd u∈[s,t−1] α[s, u, L, 1] ⊗ α[u + 1, t, R, 1] ⊗ θst

Another evidence is that you take the value α[1, n, R, 1] as the log partition where the root index is obviously the left index 1 rather than right index n.

Thanks

**Comment by yoonkim** [comment]
Ah yes, L/R meant the direction of the arrow from the subtree root. The way I described it in the appendix is certainly confusing. Sorry about that!

**Comment by berlino** [comment]
Thanks.
