### ISSUE TITLE
EisnerCRF with PyTorch

### ISSUE THREAD

**Issue by Liang-Qiu** [harvardnlp/struct-attn#4]
Hi! I am trying to use the EisnerCRF with some PyTorch Modules. Should I re-write the model in PyTorch (write a custom back-propagation method) or is this already included in the [pytorch-struct](https://github.com/harvardnlp/pytorch-struct) library? I read the documentation of pytorch-struct and it seems it only provides forward-pass right now.

**Comment by srush** [comment]
It definitely includes backprop. That's the motivation of the library! 

Let me know if the docs are unclear. Calling `crf.log_prob(log_potentials).backward()` will update all the parameters. 

Also let me know if you need any more features (there was a request for labeled arcs).

**Comment by srush** [comment]
Oh, I see this the struct-attn repo. To do struct-attn in pytorch-struct you can call `f(crf.marginals).backward()`

**Comment by Liang-Qiu** [comment]
@srush Thank you for your quick response! I see, I thought it provides forward pass only cuz I saw "Implementation uses linear-scan, forward-pass only" in the docs. I will read the docs more thoroughly. Also thanks for the great library!

**Comment by srush** [comment]
Yeah, my bad. It means "we only have to implement the forward pass". 

Let me know if you have any issues! (unfortunately this particular usage is still a bit slow, let me know what you see in terms of perf)

**Comment by Liang-Qiu** [comment]
Sure, I am testing pytorch-struct for multi-party dialog modeling. BTW, is it possible that I directly email you? I might have some questions on the algorithm.

**Comment by srush** [comment]
sure.
